name: CI
on:
  push:
  pull_request:
env:
  BuildDocEnabled: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
  CMakeVersion: 3.10.x
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-2016]
        vulkan-version: [1.2.189.0, latest]
        build-shared: [OFF]
        include:
          - build-shared: ON
            os: windows-2016
            vulkan-version: 1.2.189.0
    continue-on-error: ${{ matrix.vulkan-version == 'latest' }}
          
    steps:
    - uses: actions/checkout@v2
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.9
      with:
        cmake-version: ${{ env.CMakeVersion }}
    - name: Install Vulkan SDK
      uses: humbletim/install-vulkan-sdk@v1.1
      with:
        version: ${{ matrix.vulkan-version }}
        cache: true
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      if: matrix.os == 'windows-2016'
    - name: Build and Install VSG
      shell: bash
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
              cmake . -DBUILD_SHARED_LIBS=${{matrix.build-shared}} -A x64
              MSBuild.exe INSTALL.vcxproj -p:Configuration=Release
         elif [ "$RUNNER_OS" == "Linux" ]; then
              cmake . -DBUILD_SHARED_LIBS=${{matrix.build-shared}}
              make -j 3 && sudo make install
         elif [ "$RUNNER_OS" == "macOS" ]; then
              cmake . -DBUILD_SHARED_LIBS=${{matrix.build-shared}}
              make -j 4 && make install
         else
              echo "$RUNNER_OS not supported"
              exit 1
         fi     
